# Generated by Django 6.0.2 on 2026-03-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_readingrecord_read_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'ジャンル', 'verbose_name_plural': 'ジャンル'},
        ),
        migrations.AlterModelOptions(
            name='readingrecord',
            options={'verbose_name': '読んだ本', 'verbose_name_plural': '読んだ本'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': '状態タグ', 'verbose_name_plural': '状態タグ'},
        ),
    ]
