# Generated by Django 6.0.2 on 2026-03-13 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_genre_options_alter_readingrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_book_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('read', '読んだ本'), ('reading', '読んでる本'), ('stacked', '積読本'), ('want', '読みたい本')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '書籍',
                'verbose_name_plural': '書籍',
            },
        ),
    ]
