# Generated by Django 6.0.2 on 2026-03-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingrecord',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.genre'),
        ),
        migrations.AlterField(
            model_name='readingrecord',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.status'),
        ),
    ]
