# Generated by Django 6.0.2 on 2026-03-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_readingrecord_genre_alter_readingrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingrecord',
            name='read_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
