# Generated by Django 6.0.2 on 2026-03-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_readingrecord_read_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingrecord',
            name='emotion',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='readingrecord',
            name='reread_flag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
